### User Auth
POST http://localhost:5000/api/users/auth HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Register User
POST http://localhost:5000/api/users/ HTTP/1.1
content-type: application/json

{
    "name": "Toto",
    "email": "toto@email.to",
    "password": "toto"
}

### Logout User
POST http://localhost:5000/api/users/logout HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Get User Profile
GET http://localhost:5000/api/users/profile HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Update User Profile
PUT http://localhost:5000/api/users/profile HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}