@baseUrl = http://localhost:5000/api/users

### User Auth
POST {{baseUrl}}/auth HTTP/1.1
content-type: application/json

{
    "email": "toto@email.to",
    "password": "toto"
}

### Register User
POST {{baseUrl}}/ HTTP/1.1
content-type: application/json

{
    "name": "Toto",
    "email": "toto@email.to",
    "password": "toto"
}

### Logout User
POST {{baseUrl}}/logout HTTP/1.1
content-type: application/json

{
}

### Get User Profile
GET {{baseUrl}}/profile HTTP/1.1
content-type: application/json

{}

### Update User Profile
PUT {{baseUrl}}/profile HTTP/1.1
content-type: application/json

{
    "password": "totoro"
}